//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rtbNodeTypeMetric
    {
        public int id { get; set; }
        public int nodeTypeId { get; set; }
        public string metricKey { get; set; }
        public string description { get; set; }
        public string metricValueType { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public string rollUpAggregateConfig { get; set; }
        public string preFillValueConfig { get; set; }
        public string defaultValue { get; set; }
        public bool usePreviousValue { get; set; }
    }
}
