//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rtbNode
    {
        public int id { get; set; }
        public int nodeId { get; set; }
        public string name { get; set; }
        public bool active { get; set; }
        public int nodeTypeId { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public Nullable<System.DateTime> activationDate { get; set; }
        public Nullable<System.DateTime> deactivationDate { get; set; }
    }
}
