//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActivityLogger
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int activityId { get; set; }
        public Nullable<int> configurationId { get; set; }
        public string oldValue { get; set; }
        public string newValue { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual tbActivity tbActivity { get; set; }
        public virtual tbConfiguration tbConfiguration { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
