//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbJob()
        {
            this.tbLogActivities = new HashSet<tbLogActivity>();
            this.tbLogErrors = new HashSet<tbLogError>();
        }
    
        public long id { get; set; }
        public int jobType { get; set; }
        public string computerName { get; set; }
        public int status { get; set; }
        public Nullable<int> interval { get; set; }
        public int priority { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<System.DateTime> endDateTime { get; set; }
        public System.DateTime startAfterDateTime { get; set; }
        public Nullable<int> processId { get; set; }
        public System.DateTime aggregationStartDateTime { get; set; }
        public System.DateTime aggregationEndDateTime { get; set; }
        public System.DateTime createdDateTime { get; set; }
        public Nullable<long> parentJobId { get; set; }
        public Nullable<int> processed { get; set; }
        public bool isRecovery { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> exitCode { get; set; }
    
        public virtual tbInterval tbInterval { get; set; }
        public virtual tbJobType tbJobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogActivity> tbLogActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogError> tbLogErrors { get; set; }
        public virtual tbPriority tbPriority { get; set; }
        public virtual tbStatu tbStatu { get; set; }
    }
}
