//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNodeStatu
    {
        public long id { get; set; }
        public int nodeId { get; set; }
        public int nodeTypeId { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool status { get; set; }
        public bool originalStatus { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime updatedDate { get; set; }
    }
}
