//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNodeStatusTemp
    {
        public int nodeId { get; set; }
        public int nodeTypeId { get; set; }
        public bool value { get; set; }
        public string average { get; set; }
    }
}
