//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbActivityLoggers = new HashSet<tbActivityLogger>();
        }
    
        public int id { get; set; }
        public string userId { get; set; }
        public string name { get; set; }
        public bool active { get; set; }
        public bool hasAdminAccess { get; set; }
        public bool hasAccessToConfiguration { get; set; }
        public bool hasAccessToQueue { get; set; }
        public bool hasAccessToRefreshJob { get; set; }
        public bool hasAccessToUpdateClock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActivityLogger> tbActivityLoggers { get; set; }
    }
}
