//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbWebServer
    {
        public int id { get; set; }
        public string serverName { get; set; }
        public string serverIP { get; set; }
        public bool active { get; set; }
        public string InstanceName { get; set; }
    }
}
