//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetAggregatedStdDev
    {
        public int nodeTypeId { get; set; }
        public int nodeId { get; set; }
        public string metricKey { get; set; }
        public Nullable<System.DateTime> reportingtimestamp { get; set; }
        public Nullable<double> stdDev { get; set; }
    }
}
