//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetJob
    {
        public long id { get; set; }
        public string JobType { get; set; }
        public string computerName { get; set; }
        public int StatusId { get; set; }
        public string Status { get; set; }
        public Nullable<int> IntervalId { get; set; }
        public string Interval { get; set; }
        public int PriorityId { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<System.DateTime> endDateTime { get; set; }
        public System.DateTime startAfterDateTime { get; set; }
        public Nullable<int> processId { get; set; }
        public System.DateTime aggregationStartDateTime { get; set; }
        public System.DateTime aggregationEndDateTime { get; set; }
        public System.DateTime createdDateTime { get; set; }
        public Nullable<int> processed { get; set; }
        public bool isRecovery { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> exitCode { get; set; }
        public string listOfJobs { get; set; }
    }
}
