//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetAggregatedBase
    {
        public int nodeTypeId { get; set; }
        public string metricKey { get; set; }
        public int nodeid { get; set; }
        public Nullable<System.DateTime> reportingtimestamp { get; set; }
        public Nullable<double> average { get; set; }
        public Nullable<double> sum { get; set; }
        public Nullable<double> min { get; set; }
        public Nullable<double> max { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> first { get; set; }
        public Nullable<int> last { get; set; }
    }
}
