//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetPreviousNodeStatusValue
    {
        public long id { get; set; }
        public Nullable<int> elapsedTime { get; set; }
        public int defaultvalue { get; set; }
    }
}
