//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aggregation_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwNode
    {
        public int id { get; set; }
        public string name { get; set; }
        public bool active { get; set; }
        public int nodeTypeId { get; set; }
        public int connectorId { get; set; }
        public string connectorCreds { get; set; }
        public string sourceInfo { get; set; }
        public int pollerId { get; set; }
        public bool useMetricTemplate { get; set; }
        public Nullable<int> nodeTypeTemplateId { get; set; }
        public int pollingInterval { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public string pollPolicy { get; set; }
        public Nullable<System.DateTime> lastPollDate { get; set; }
        public Nullable<System.DateTime> nextPollDate { get; set; }
        public string nodeData { get; set; }
        public string processorName { get; set; }
        public Nullable<System.DateTime> activationDate { get; set; }
        public Nullable<System.DateTime> deactivationDate { get; set; }
    }
}
